{% set name = "imaxt-multiscale-plugin" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imaxt-multiscale-plugin-{{ version }}.tar.gz
  sha256: 56cd7039425656c82925f9016c3eefe5e17f73244d19177d2127c23bf23ba2c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - astropy
    - dask-core
    - imageio
    - imaxt-image
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - s3fs
    - xarray
    - zarr




test:
  imports:
    - imaxt_multiscale_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://gitlab.developers.cam.ac.uk/astronomy/camcead/imaxt/imaxt-multiscale-plugin
  summary: A simple plugin to use with napari
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eddienko
    - goanpeca
    - jaimergp
